### ISSUE TITLE
model user

### ISSUE THREAD

**Issue by guilodron** [guilodron/trabalho-final-struct#5]
Create User Model {
- name 
- email
- password
- picture
- reviews
- movies seen
- favorite genres
- about/bio
}

**Comment by Leir-Cruz** [comment]
> Create User Model {
> 
>     * name
> 
>     * email
> 
>     * password
> 
>     * picture
> 
>     * reviews
> 
>     * movies seen
> 
>     * favorite genres
> 
>     * about/bio
>       }
